behaviors:
  BallEngineAIBIG:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 1.0e-3
      epsilon: 0.15
      lambd: 0.92
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 40
    max_steps: 9.00e10
    time_horizon: 128
    summary_freq: 50000
    threaded: true